[build]
packages = ["python3", "python3-pip", "nodejs", "npm"]

command = """
cd toji-project
pip install -r requirements.txt
cd webapp && npm install && npm run build
"""

[start]
command = """
cd toji-project
python backend/main.py &
python bot/toji_bot.py &
cd webapp && npm run dev
"""
